List<String> navTitles = [
  "Home",
  "About",
  "Contact",
  // "Request Relief",
  // "Admin",
];
List<String> navLinks = [
  "/",
  "/",
  "/",
  "/requestrelief",
  "/",
];

// List<dynamic> bgrgyList = [
//   ['1', 'BARANGAY I-A'],
//   ['2', 'BARANGAY I-B'],
//   ['3', 'BARANGAY BAGONG BAYAN (1-C)'],
//   ['4', 'BARANGAY II-A'],
//   ['5', 'Bagong Pook IV-A'],
//   ['6', 'BARANGAY II-B'],
//   ['7', 'BARANGAY II-C'],
//   ['8', 'BARANGAY II-D'],
//   ['9', 'BARANGAY II-E'],
//   ['10', 'BARANGAY II-F'],
//   ['11', 'BARANGAY III-A'],
//   ['12', 'BARANGAY III-B'],
//   ['13', 'BARANGAY III-C'],
//   ['14', 'BARANGAY III-D'],
//   ['15', 'BARANGAY III-E'],
//   ['16', 'BARANGAY III-F'],
//   ['17', 'BARANGAY IV-A'],
//   ['18', 'BARANGAY IV-B'],
//   ['19', 'BARANGAY IV-C'],
//   ['20', 'BARANGAY V-A'],
//   ['21', 'BARANGAY V-B'],
//   ['22', 'BARANGAY V-C'],
//   ['23', 'BARANGAY V-D'],
//   ['24', 'BARANGAY VI-A'],
//   ['25', 'BARANGAY VI-B'],
//   ['26', 'BARANGAY BAGONG POOK (VI-C)'],
//   ['27', 'BARANGAY VI-D'],
//   ['28', 'BARANGAY VI-E'],
//   ['29', 'BARANGAY VII-A'],
//   ['30', 'BARANGAY VII-B'],
//   ['31', 'BARANGAY VII-C'],
//   ['32', 'BARANGAY VII-D'],
//   ['33', 'BARANGAY VII-E'],
//   ['34', 'BARANGAY CONCEPCION'],
//   ['35', 'BARANGAY DOLORES'],
//   ['36', 'BARANGAY SAN BUENAVENTURA'],
//   ['37', 'BARANGAY DIEGO'],
//   ['38', 'BARANGAY LORENZO'],
//   ['39', 'BARANGAY SAN PEDRO'],
//   ['40', 'BARANGAY STA. CATALINA'],
//   ['41', 'BARANGAY STA. ISABEL'],
//   ['42', 'BARANGAY STO. ANGEL'],
//   ['43', 'BARANGAY SAN CRISTOBAL'],
//   ['44', 'BARANGAY STA. ELENA'],
//   ['45', 'BARANGAY STO. NIÑO'],
//   ['46', 'BARANGAY BAUTISTA'],
//   ['47', 'BARANGAY SAN BARTOLOME'],
//   ['48', 'BARANGAY SAN ROQUE'],
//   ['49', 'BARANGAY SANTIAGO 1'],
//   ['50', 'BARANGAY SANTIAGO 2'],
//   ['51', 'BARANGAY STA. MONICA'],
//   ['52', 'BARANGAY STA. VERONICA'],
//   ['53', 'BARANGAY DEL REMEDIO'],
//   ['54', 'BARANGAY SAN CRISPIN'],
//   ['55', 'BARANGAY SAN JUAN'],
//   ['56', 'BARANGAY SAN LUCAS 1'],
//   ['57', 'BARANGAY SAN LUCAS 2'],
//   ['58', 'BARANGAY SAN MARCOS'],
//   ['59', 'BARANGAY SAN MATEO'],
//   ['60', 'BARANGAY SAN NICOLAS'],
//   ['61', 'BARANGAY SAN RAFAEL'],
//   ['62', 'BARANGAY STA. FILOMENA'],
//   ['63', 'BARANGAY STA. MARIA MAGDALENA'],
//   ['64', 'BARANGAY SAN GABRIEL'],
//   ['65', 'BARANGAY STA. MARIA'],
//   ['66', 'BARANGAY SAN MIGUEL'],
//   ['67', 'BARANGAY STO. ROSARIO'],
//   ['68', 'BARANGAY ATISAN'],
//   ['69', 'BARANGAY SAN ANTONIO 1'],
//   ['70', 'BARANGAY SAN ANTONIO 2'],
//   ['71', 'BARANGAY SAN FRANCISCO'],
//   ['72', 'BARANGAY SAN GREGORIO'],
//   ['73', 'BARANGAY SAN IGNACIO'],
//   ['74', 'BARANGAY SAN ISIDRO'],
//   ['75', 'BARANGAY SAN JOAQUIN'],
//   ['76', 'BARANGAY SAN JOSE'],
//   ['77', 'BARANGAY SAN VICENTE'],
//   ['78', 'BARANGAY STA.ANA'],
//   ['79', 'BARANGAY STA.CRUZ'],
//   ['80', 'BARANGAY STO. CRISTO'],
// ];

List<String> bgrgyList = [
  'BARANGAY I-A',
  'BARANGAY I-B',
  'BARANGAY BAGONG BAYAN (1-C)',
  'BARANGAY II-A',
  'Bagong Pook IV-A',
  'BARANGAY II-B',
  'BARANGAY II-C',
  'BARANGAY II-D',
  'BARANGAY II-E',
  'BARANGAY II-F',
  'BARANGAY III-A',
  'BARANGAY III-B',
  'BARANGAY III-C',
  'BARANGAY III-D',
  'BARANGAY III-E',
  'BARANGAY III-F',
  'BARANGAY IV-A',
  'BARANGAY IV-B',
  'BARANGAY IV-C',
  'BARANGAY V-A',
  'BARANGAY V-B',
  'BARANGAY V-C',
  'BARANGAY V-D',
  'BARANGAY VI-A',
  'BARANGAY VI-B',
  'BARANGAY BAGONG POOK (VI-C)',
  'BARANGAY VI-D',
  'BARANGAY VI-E',
  'BARANGAY VII-A',
  'BARANGAY VII-B',
  'BARANGAY VII-C',
  'BARANGAY VII-D',
  'BARANGAY VII-E',
  'BARANGAY CONCEPCION',
  'BARANGAY DOLORES',
  'BARANGAY SAN BUENAVENTURA',
  'BARANGAY DIEGO',
  'BARANGAY LORENZO',
  'BARANGAY SAN PEDRO',
  'BARANGAY STA. CATALINA',
  'BARANGAY STA. ISABEL',
  'BARANGAY STO. ANGEL',
  'BARANGAY SAN CRISTOBAL',
  'BARANGAY STA. ELENA',
  'BARANGAY STO. NIÑO',
  'BARANGAY BAUTISTA',
  'BARANGAY SAN BARTOLOME',
  'BARANGAY SAN ROQUE',
  'BARANGAY SANTIAGO 1',
  'BARANGAY SANTIAGO 2',
  'BARANGAY STA. MONICA',
  'BARANGAY STA. VERONICA',
  'BARANGAY DEL REMEDIO',
  'BARANGAY SAN CRISPIN',
  'BARANGAY SAN JUAN',
  'BARANGAY SAN LUCAS 1',
  'BARANGAY SAN LUCAS 2',
  'BARANGAY SAN MARCOS',
  'BARANGAY SAN MATEO',
  'BARANGAY SAN NICOLAS',
  'BARANGAY SAN RAFAEL',
  'BARANGAY STA. FILOMENA',
  'BARANGAY STA. MARIA MAGDALENA',
  'BARANGAY SAN GABRIEL',
  'BARANGAY STA. MARIA',
  'BARANGAY SAN MIGUEL',
  'BARANGAY STO. ROSARIO',
  'BARANGAY ATISAN',
  'BARANGAY SAN ANTONIO 1',
  'BARANGAY SAN ANTONIO 2',
  'BARANGAY SAN FRANCISCO',
  'BARANGAY SAN GREGORIO',
  'BARANGAY SAN IGNACIO',
  'BARANGAY SAN ISIDRO',
  'BARANGAY SAN JOAQUIN',
  'BARANGAY SAN JOSE',
  'BARANGAY SAN VICENTE',
  'BARANGAY STA.ANA',
  'BARANGAY STA.CRUZ',
  'BARANGAY STO. CRISTO',
];



List<String> officeList = [
  'CWSDO',
  'BARANGAY I-A',
  'BARANGAY I-B',
  'BARANGAY BAGONG BAYAN (1-C)',
  'BARANGAY II-A',
  'Bagong Pook IV-A',
  'BARANGAY II-B',
  'BARANGAY II-C',
  'BARANGAY II-D',
  'BARANGAY II-E',
  'BARANGAY II-F',
  'BARANGAY III-A',
  'BARANGAY III-B',
  'BARANGAY III-C',
  'BARANGAY III-D',
  'BARANGAY III-E',
  'BARANGAY III-F',
  'BARANGAY IV-A',
  'BARANGAY IV-B',
  'BARANGAY IV-C',
  'BARANGAY V-A',
  'BARANGAY V-B',
  'BARANGAY V-C',
  'BARANGAY V-D',
  'BARANGAY VI-A',
  'BARANGAY VI-B',
  'BARANGAY BAGONG POOK (VI-C)',
  'BARANGAY VI-D',
  'BARANGAY VI-E',
  'BARANGAY VII-A',
  'BARANGAY VII-B',
  'BARANGAY VII-C',
  'BARANGAY VII-D',
  'BARANGAY VII-E',
  'BARANGAY CONCEPCION',
  'BARANGAY DOLORES',
  'BARANGAY SAN BUENAVENTURA',
  'BARANGAY DIEGO',
  'BARANGAY LORENZO',
  'BARANGAY SAN PEDRO',
  'BARANGAY STA. CATALINA',
  'BARANGAY STA. ISABEL',
  'BARANGAY STO. ANGEL',
  'BARANGAY SAN CRISTOBAL',
  'BARANGAY STA. ELENA',
  'BARANGAY STO. NIÑO',
  'BARANGAY BAUTISTA',
  'BARANGAY SAN BARTOLOME',
  'BARANGAY SAN ROQUE',
  'BARANGAY SANTIAGO 1',
  'BARANGAY SANTIAGO 2',
  'BARANGAY STA. MONICA',
  'BARANGAY STA. VERONICA',
  'BARANGAY DEL REMEDIO',
  'BARANGAY SAN CRISPIN',
  'BARANGAY SAN JUAN',
  'BARANGAY SAN LUCAS 1',
  'BARANGAY SAN LUCAS 2',
  'BARANGAY SAN MARCOS',
  'BARANGAY SAN MATEO',
  'BARANGAY SAN NICOLAS',
  'BARANGAY SAN RAFAEL',
  'BARANGAY STA. FILOMENA',
  'BARANGAY STA. MARIA MAGDALENA',
  'BARANGAY SAN GABRIEL',
  'BARANGAY STA. MARIA',
  'BARANGAY SAN MIGUEL',
  'BARANGAY STO. ROSARIO',
  'BARANGAY ATISAN',
  'BARANGAY SAN ANTONIO 1',
  'BARANGAY SAN ANTONIO 2',
  'BARANGAY SAN FRANCISCO',
  'BARANGAY SAN GREGORIO',
  'BARANGAY SAN IGNACIO',
  'BARANGAY SAN ISIDRO',
  'BARANGAY SAN JOAQUIN',
  'BARANGAY SAN JOSE',
  'BARANGAY SAN VICENTE',
  'BARANGAY STA.ANA',
  'BARANGAY STA.CRUZ',
  'BARANGAY STO. CRISTO',
];



//
//
//
//
// BARANGAY II-D
// BARANGAY II-E
// BARANGAY II-F
// BARANGAY III-A
// BARANGAY III-B
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//

List<TableEntry> entries = [
  TableEntry(name: 'John Doe', age: 28, email: 'john.doe@example.com'),
  TableEntry(name: 'Jane Smith', age: 34, email: 'jane.smith@example.com'),
  // Add more entries as needed
];

class TableEntry {
  final String name;
  final int age;
  final String email;

  TableEntry({required this.name, required this.age, required this.email});
}
