// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCysOOowZfLAvpHzoPHjW0X0ABJLoAWMPk',
    appId: '1:425863721054:web:7ad77af9c53453a3c744cf',
    messagingSenderId: '425863721054',
    projectId: 'cswdo-app',
    authDomain: 'cswdo-app.firebaseapp.com',
    storageBucket: 'cswdo-app.appspot.com',
    measurementId: 'G-6N2R589HWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAResQi7k-_E_ZEIMdiw-UtPz9fekkItWQ',
    appId: '1:425863721054:android:3283877ca2946983c744cf',
    messagingSenderId: '425863721054',
    projectId: 'cswdo-app',
    storageBucket: 'cswdo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRAlmTJ5ZSBAm4fEL8H2tJc3nCw6Blfog',
    appId: '1:425863721054:ios:582fb9ca61f3671ec744cf',
    messagingSenderId: '425863721054',
    projectId: 'cswdo-app',
    storageBucket: 'cswdo-app.appspot.com',
    iosBundleId: 'com.example.cwsdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRAlmTJ5ZSBAm4fEL8H2tJc3nCw6Blfog',
    appId: '1:425863721054:ios:582fb9ca61f3671ec744cf',
    messagingSenderId: '425863721054',
    projectId: 'cswdo-app',
    storageBucket: 'cswdo-app.appspot.com',
    iosBundleId: 'com.example.cwsdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCysOOowZfLAvpHzoPHjW0X0ABJLoAWMPk',
    appId: '1:425863721054:web:984a5e33283926bec744cf',
    messagingSenderId: '425863721054',
    projectId: 'cswdo-app',
    authDomain: 'cswdo-app.firebaseapp.com',
    storageBucket: 'cswdo-app.appspot.com',
    measurementId: 'G-2Q83ZDPEYQ',
  );

}